interface dummyDataTypes {
  [key: string]: any;
}

export const dummyData: dummyDataTypes = {
  info: {
    contentId: 1914920,
    title: "JW 메리어트 동대문 스퀘어 서울",
    category: "관광호텔",
    homepage:
      '<a href="http://www.jwmarriottddm.com" target="_blank" title="새창 : JW 메리어트 동대문 스퀘어 서울 홈페이지로 이동">http://www.jwmarriottddm.com</a>',
    firstImage: "0",
    firstImage2: null,
    areaCode: 0,
    addr1: "서울특별시 종로구 청계천로 279",
    addr2: null,
    mapX: 127.00666,
    mapY: 37.573105,
    deaf: 1,
    visuallyImpaired: 0,
    mobilityWeak: 1,
    old: 1,
    infant: 1,
    hit: 0, // 조회수
    barrier: {
      parking: "장애인 주차장 있음(7대)_무장애 편의시설",
      route: "",
      publicTransport: "출입구까지 턱이 없어 휠체어 접근 가능함",
      ticketOffice: "",
      promotion: "",
      wheelchair: "대여가능",
      exit: "주출입구는 턱이 없어 휠체어 접근 가능함",
      elevator: "엘리베이터 있음",
      restroom: "장애인 화장실 있음(로비 2개, LL층 2개)",
      auditorium: "",
      room: "장애인 객실 있음(1실, 일반 객실 입구에 턱이 없음)",
      handicapEtc: "",
      braileBlock:
        "점자블록 있음(엘리베이터,홀,장애인 난간대)_시각장애인 편의시설",
      helpDog: "",
      guideHuman: "",
      audioGuide: "",
      bigPrint: "",
      brailePromotion: "",
      guideSystem: "",
      blindHandicapEtc: "",
      signGuide: "",
      videoGuide: "",
      hearingRoom: "",
      hearingHandicapEtc: "",
      stroller: "",
      lactationRoom: "",
      babySpareChair: "",
      infantsFamilyEtc: "",
    },
    checkInTime: "15:00",
    checkOutTime: "12:00",
    isCooking: "0",
    foodPlace: null,
    hanok: 0,
    infoCenter: "02-2276-3000",
    commonParking: "주차가능",
    pickup: "0",
    reservationUrl:
      '<a href="http://www.jwmarriottddm.com" target="_blank" title="새창 : JW 메리어트 동대문 스퀘어 서울 홈페이지로 이동">http://www.jwmarriottddm.com</a>',
    subFacility: "스파 바이 록시땅, 피트니스클럽, 실내 수영장, 웨딩홀",
    barbecue: 0,
    fitness: 0,
    beverage: 0,
    bicycle: 0,
    campfire: 0,
    karaoke: 0,
    publicBath: 0,
    publicPc: 0,
    sauna: 0,
    sports: 0,
    refundRegulation: "0",
    liked: false,
    mlevel: 6,
  },
};
